




WITH dept AS 
(
SELECT 
ROW_NUMBER() OVER(ORDER BY DATE) AS ROW_NUM,
TO_CHAR(DATE, '%Y-%m-%d') AS DATE_ID,
STORE AS STORE_ID,
DEPT AS DEPT_ID,
DATE AS STORE_DATE,
WEEKLY_SALES AS STORE_WEEKLY_SALES,
ISHOLIDAY,
CURRENT_TIMESTAMP(6) AS INSERT_DATE
FROM {{source('bronze_data','DEPARTMENT_RAW')}}
)

SELECT * FROM dept