WITH raw_fact AS (
    SELECT
        STORE AS STORE_ID,
        TO_CHAR(DATE, '%Y-%m-%d') AS DATE_ID,
        TEMPERATURE,
        FUEL_PRICE,
        CASE WHEN MARKDOWN1 = 'NA' THEN 0 ELSE CAST(MARKDOWN1 AS FLOAT) END AS MARKDOWN1,
        CASE WHEN MARKDOWN2 = 'NA' THEN 0 ELSE CAST(MARKDOWN2 AS FLOAT) END AS MARKDOWN2,
        CASE WHEN MARKDOWN3 = 'NA' THEN 0 ELSE CAST(MARKDOWN3 AS FLOAT) END AS MARKDOWN3,
        CASE WHEN MARKDOWN4 = 'NA' THEN 0 ELSE CAST(MARKDOWN4 AS FLOAT) END AS MARKDOWN4,
        CASE WHEN MARKDOWN5 = 'NA' THEN 0 ELSE CAST(MARKDOWN5 AS FLOAT) END AS MARKDOWN5,
        CASE WHEN CPI = 'NA' THEN 0 ELSE CAST(CPI AS FLOAT) END AS CPI,
        CASE WHEN UNEMPLOYMENT = 'NA' THEN 0 ELSE CAST(UNEMPLOYMENT AS FLOAT) END AS UNEMPLOYMENT,
        ISHOLIDAY,
        CURRENT_TIMESTAMP(6) AS INSERT_DATE,
        CURRENT_TIMESTAMP(6) AS VRSN_START_DATE,
        CURRENT_TIMESTAMP(6) AS VRSN_END_DATE
    FROM {{source('bronze_data','FACT_RAW')}}
)

SELECT * FROM raw_fact