




WITH walmart_date_dim AS 
(
SELECT 
TO_CHAR(DATE, '%Y-%m-%d') AS DATE_ID,
DATE,
ISHOLIDAY,
CURRENT_TIMESTAMP(6) AS INSERT_DATE,
CURRENT_TIMESTAMP(6) AS UPDATE_DATE
FROM {{source('bronze_data','DEPARTMENT_RAW')}}
)

SELECT * FROM walmart_date_dim