-- Create a structured table since this is CSV, if JSON then use variant
CREATE OR REPLACE TABLE MYDB.PUBLIC.DIM_DEPARTMENT_RAW
(
    STORE INTEGER,
    DEPT INTEGER,
    DATE DATE,
    WEEKLY_SALES FLOAT,
    ISHOLIDAY VARCHAR(50),
    INSERT_DATE TIMESTAMP(6),
    UPDATE_DATE TIMESTAMP(6)
);

COPY INTO MYDB.PUBLIC.DIM_DEPARTMENT_RAW (STORE, DEPT, DATE, WEEKLY_SALES, ISHOLIDAY)
FROM @MYDB.PUBLIC.WALMART_STAGE/department.csv
FILE_FORMAT = MYDB.PUBLIC.MY_CSV_FORMAT;

-- select * from mydb.public.dim_department_raw;

CREATE OR REPLACE TABLE MYDB.PUBLIC.DIM_STORES_RAW
(
STORE INTEGER,
TYPE VARCHAR(10),
SIZE INTEGER,
INSERT_DATE TIMESTAMP(6),
UPDATE_DATE TIMESTAMP(6)
);

COPY INTO MYDB.PUBLIC.DIM_STORES_RAW
(
STORE,
TYPE,
SIZE
)
FROM @MYDB.PUBLIC.WALMART_STAGE/stores.csv
FILE_FORMAT = MYDB.PUBLIC.MY_CSV_FORMAT;

-- select * from mydb.public.dim_stores_raw;

CREATE OR REPLACE TABLE MYDB.PUBLIC.FACT_RAW
(
STORE INTEGER,
DATE DATE,
TEMPERATURE DECIMAL,
FUEL_PRICE DECIMAL,
MARKDOWN1 VARCHAR(255),
MARKDOWN2 VARCHAR(255),
MARKDOWN3 VARCHAR(255),
MARKDOWN4 VARCHAR(255),
MARKDOWN5 VARCHAR(255),
CPI VARCHAR(255),
UNEMPLOYMENT VARCHAR(255),
ISHOLIDAY VARCHAR(50),
INSERT_DATE TIMESTAMP(6),
UPDATE_DATE TIMESTAMP(6),
VRSN_START_DATE TIMESTAMP(6),
VRSN_END_DATE TIMESTAMP(6)
);

COPY INTO MYDB.PUBLIC.FACT_RAW
(
STORE,
DATE,
TEMPERATURE,
FUEL_PRICE,
MARKDOWN1,
MARKDOWN2,
MARKDOWN3,
MARKDOWN4,
MARKDOWN5,
CPI,
UNEMPLOYMENT,
ISHOLIDAY
)
FROM @MYDB.PUBLIC.WALMART_STAGE/fact.csv
FILE_FORMAT = MYDB.PUBLIC.MY_CSV_FORMAT;

select * from mydb.public.fact_raw;