CREATE OR REPLACE PIPE MYDB.PUBLIC.DEPARTMENTPIPE
AUTO_INGEST = TRUE AS
COPY INTO MYDB.PUBLIC.DIM_DEPARTMENT_RAW
FROM
(
SELECT
$1 AS STORE,
$2 AS DEPT,
$3 AS DATE,
$4 AS WEEKLY_SALE,
$5 AS ISHOLIDAY
FROM @MYDB.PUBLIC.WALMART_STAGE/department.csv
)
FILE_FORMAT = MYDB.PUBLIC.MY_CSV_FORMAT;

-- check if pipe is running
-- SELECT SYSTEM$PIPE_STATUS('MYDB.PUBLIC.DEPARTMENTPIPE');

CREATE OR REPLACE PIPE MYDB.PUBLIC.STOREPIPE
AUTO_INGEST = TRUE AS
COPY INTO MYDB.PUBLIC.DIM_STORES_RAW
FROM
(
SELECT
$1 AS STORE,
$2 AS TYPE,
$3 AS SIZE
FROM @MYDB.PUBLIC.WALMART_STAGE/stores.csv
)
FILE_FORMAT = MYDB.PUBLIC.MY_CSV_FORMAT;

CREATE OR REPLACE PIPE MYDB.PUBLIC.FACTPIPE
AUTO_INGEST = TRUE AS
COPY INTO MYDB.PUBLIC.FACT_RAW
FROM
(
SELECT
$1 AS STORE,
$2 AS DATE,
$3 AS TEMPERATURE,
$4 AS FUEL_PRICE,
$5 AS MARKDOWN1,
$6 AS MARKDOWN2,
$7 AS MARKDOWN3,
$8 AS MARKDOWN4,
$9 AS MARKDOWN5,
$10 AS CPI,
$11 AS UNEMPLOYMENT,
$12 AS ISHOLIDAY
FROM @MYDB.PUBLIC.WALMART_STAGE/fact.csv
)
FILE_FORMAT = MYDB.PUBLIC.MY_CSV_FORMAT;

USE SCHEMA MYDB.PUBLIC;
SHOW PIPES;

ls @MYDB.PUBLIC.WALMART_STAGE;

select * from MYDB.PUBLIC.DIM_DEPARTMENT_RAW;

ALTER PIPE MYDB.PUBLIC.DEPARTMENTPIPE SET PIPE_EXECUTION_PAUSED = TRUE;
ALTER PIPE MYDB.PUBLIC.STOREPIPE SET PIPE_EXECUTION_PAUSED = TRUE;
ALTER PIPE MYDB.PUBLIC.FACTPIPE SET PIPE_EXECUTION_PAUSED = TRUE;