USE ROLE ACCOUNTADMIN;
USE WAREHOUSE compute_wh;

CREATE OR REPLACE DATABASE MYDB;


CREATE OR REPLACE STORAGE INTEGRATION WALMART_S3_INT

  TYPE = EXTERNAL_STAGE

  STORAGE_PROVIDER = 'S3'

  ENABLED = TRUE

  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::012178638860:role/walmart-snowflake-project-role'

  STORAGE_ALLOWED_LOCATIONS = ('s3://walmart-e2e-project-012178638860-us-east-1-an/raw_data/');

  -- Create trust between Snowflake and AWS

DESC INTEGRATION WALMART_S3_INT;


  CREATE OR REPLACE FILE FORMAT MYDB.PUBLIC.MY_CSV_FORMAT

  TYPE = CSV

  FIELD_DELIMITER = ','

  FIELD_OPTIONALLY_ENCLOSED_BY = '"'

  SKIP_HEADER = 1

  NULL_IF = ('NULL', 'null')

  EMPTY_FIELD_AS_NULL = true;


CREATE OR REPLACE STAGE MYDB.PUBLIC.WALMART_STAGE

STORAGE_INTEGRATION = WALMART_S3_INT

URL= 's3://walmart-e2e-project-012178638860-us-east-1-an/raw_data/'

FILE_FORMAT = MYDB.PUBLIC.MY_CSV_FORMAT;

ls @MYDB.PUBLIC.WALMART_STAGE;

