-- This sql worksheet sets up the schemas, storage location and stage for data to be ingested into bronze layer

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE AIRFLOW_DB;

USE DATABASE AIRFLOW_DB;

CREATE OR REPLACE SCHEMA BRONZE;

CREATE OR REPLACE SCHEMA SILVER;

CREATE OR REPLACE SCHEMA GOLD;

-- USE Bronze schema for S3 storage
USE SCHEMA AIRFLOW_DB.BRONZE;



CREATE OR REPLACE STORAGE INTEGRATION AIRFLOW_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::012178638860:role/airflow_snowflake_project'
    STORAGE_ALLOWED_LOCATIONS = ('s3://dea-airflow-databucket');

DESC INTEGRATION AIRFLOW_S3_INT;


CREATE OR REPLACE STAGE AIRFLOW_DB.BRONZE.AIRFLOW_S3_STAGE
STORAGE_INTEGRATION = AIRFLOW_S3_INT
URL = 's3://dea-airflow-databucket';

ls @AIRFLOW_DB.BRONZE.AIRFLOW_S3_STAGE;






