

WITH department_raw AS 
(
SELECT 
STORE AS STORE_ID,
DEPT AS DEPT_ID,
DATE,
WEEKLY_SALE,
ISHOLIDAY,
TIMESTAMP AS INSERT_DATE,
TIMESTAMP AS UPDDATE_DATE
FROM {{source('department_data','DIM_DEPARTMENT_RAW')}}
)

SELECT * FROM department_raw